### ISSUE TITLE
Possible issue around caching on apnews.com

### ISSUE THREAD

**Issue by imsofi** [html2rss/html2rss-web#472]
When attempting to use the new configuration in the following PR: https://github.com/html2rss/html2rss-configs/pull/176 I seem to have hit an issue around the caching of dynamic config files. I have yet to figure out a good set of steps to reproduce, or find the root cause of where exactly it goes wrong. But what i have done is this:

Try to load `section=trending-news` then shortly after attempt to load another, for example `section=ukraine`. It will either mix the stories from both trending-news and ukraine. Or only load the previous trending-news news stories under ukraine.

My feeling is that it might have to do with these pages taking a bit to load, and there are errors seeming to be around timeouts. But this might be the wrong path to go down. You can see the logs below:

```
[1] Puma starting in cluster mode...
[1] * Puma version: 5.6.2 (ruby 3.1.1-p18) ("Birdie's Version")
[1] *  Min threads: 5
[1] *  Max threads: 5
[1] *  Environment: production
[1] *   Master PID: 1
[1] *      Workers: 2
[1] *     Restarts: (✔) hot (✖) phased
[1] * Preloading application
[1] * Listening on http://0.0.0.0:3000
[1] Use Ctrl-C to stop
[1] - Worker 0 (PID: 3) booted in 0.0s, phase: 0
[1] - Worker 1 (PID: 4) booted in 0.0s, phase: 0
source=rack-timeout id=0894f721-5348-4ba2-9fac-0fffcabb1078 timeout=15000ms state=ready at=info
/usr/local/bundle/bundler/gems/html2rss-a898923f92b2/lib/html2rss/item_extractors/href.rb:26: warning: redefining constant Struct::Options
/usr/local/bundle/bundler/gems/html2rss-a898923f92b2/lib/html2rss/item_extractors/html.rb:25: warning: redefining constant Struct::Options
/usr/local/bundle/bundler/gems/html2rss-a898923f92b2/lib/html2rss/item_extractors/static.rb:16: warning: redefining constant Struct::Options
/usr/local/bundle/bundler/gems/html2rss-a898923f92b2/lib/html2rss/item_extractors/text.rb:23: warning: redefining constant Struct::Options
source=rack-timeout id=0894f721-5348-4ba2-9fac-0fffcabb1078 timeout=15000ms service=1462ms state=completed at=info
source=rack-timeout id=45b4009a-7b73-4652-b7d2-fc2e84178fe1 timeout=15000ms state=ready at=info
source=rack-timeout id=45b4009a-7b73-4652-b7d2-fc2e84178fe1 timeout=15000ms service=1ms state=completed at=info
source=rack-timeout id=a2bd4d83-a7b9-420e-b131-668b5394abc3 timeout=15000ms state=ready at=info
source=rack-timeout id=a2bd4d83-a7b9-420e-b131-668b5394abc3 timeout=15000ms service=1ms state=completed at=info
source=rack-timeout id=1e97365c-5228-4d84-a3b2-c3b401cd06d5 timeout=15000ms state=ready at=info
source=rack-timeout id=1e97365c-5228-4d84-a3b2-c3b401cd06d5 timeout=15000ms service=4ms state=completed at=info
source=rack-timeout id=a2720804-beca-41de-9003-194396ef1a69 timeout=15000ms state=ready at=info
source=rack-timeout id=9f3a171e-3956-47fc-8eed-cd3fe10a51a0 timeout=15000ms state=ready at=info
source=rack-timeout id=a2720804-beca-41de-9003-194396ef1a69 timeout=15000ms service=2ms state=completed at=info
source=rack-timeout id=9f3a171e-3956-47fc-8eed-cd3fe10a51a0 timeout=15000ms service=1ms state=completed at=info
source=rack-timeout id=ad960dbb-d315-4752-8229-fc42159466d8 timeout=15000ms state=ready at=info
source=rack-timeout id=ad960dbb-d315-4752-8229-fc42159466d8 timeout=15000ms service=1ms state=completed at=info
source=rack-timeout id=806abc6b-43c8-4479-ba37-0ad93475f3a3 timeout=15000ms state=ready at=info
/usr/local/bundle/bundler/gems/html2rss-a898923f92b2/lib/html2rss/item_extractors/href.rb:26: warning: redefining constant Struct::Options
/usr/local/bundle/bundler/gems/html2rss-a898923f92b2/lib/html2rss/item_extractors/html.rb:25: warning: redefining constant Struct::Options
/usr/local/bundle/bundler/gems/html2rss-a898923f92b2/lib/html2rss/item_extractors/static.rb:16: warning: redefining constant Struct::Options
/usr/local/bundle/bundler/gems/html2rss-a898923f92b2/lib/html2rss/item_extractors/text.rb:23: warning: redefining constant Struct::Options
source=rack-timeout id=806abc6b-43c8-4479-ba37-0ad93475f3a3 timeout=15000ms service=4094ms state=completed at=info
source=rack-timeout id=2c4a2607-64e9-44ca-9732-bbaace89398b timeout=15000ms state=ready at=info
source=rack-timeout id=2c4a2607-64e9-44ca-9732-bbaace89398b timeout=15000ms service=634ms state=completed at=info
source=rack-timeout id=de17384a-22f5-4aac-8295-f79e2c6c5204 timeout=15000ms state=ready at=info
source=rack-timeout id=de17384a-22f5-4aac-8295-f79e2c6c5204 timeout=15000ms service=364ms state=completed at=info
```

**Comment by imsofi** [comment]
Okay so after some digging into what i was doing a month ago i figured it out. The currently shipped `apnews` config works flawlessly. I failed however to say that i was extending apnews using my own custom `feeds.yml` file with my own apnews.com scraper:

```yml
# config/feeds.yml
stylesheets:
  - href: '/rss.xsl'
    media: 'all'
    type: 'text/xsl'
headers:
  "User-Agent": "Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0"
feeds:
  apnewshub:
    channel:
      url: https://apnews.com/hub/%<section>s
      language: en
      ttl: 120
      time_zone: UTC
    selectors:
      items:
        selector: ".FeedCard"
      title:
        selector: h2
      link:
        selector: a:first
        extractor: href
      description:
        selector: p
        post_process:
          name: gsub
          pattern: '^COPENHAGEN, Denmark \(AP\) \— '
          replacement: ''
      updated:
        selector: ".Timestamp"
        extractor: attribute
        attribute: data-source
        post_process:
          name: "parse_time"
      author:
        selector: 'span[class^="Component-bylines"]'
        post_process:
          - name: gsub
            pattern: '^By '
            replacement: ''
          - name: gsub
            pattern: '^$'
            replacement: 'APNEWS'
```

This configuration does fail if you go to `http://localhost:3000/apnewshub.rss?section=denmark` then quickly thereafter `http://localhost:3000/apnewshub.rss?section=ukraine`. However, this works properly when using `curl` and the ruby comparison you provided, but it does load wrongly under chromium, see attached pictures below.

![09 Thu 22:43:24](https://user-images.githubusercontent.com/20756843/172940941-ca6f25bd-1026-4677-873f-6d7a6e6d3fad.png)
![09 Thu 22:43:11](https://user-images.githubusercontent.com/20756843/172940936-22254a98-c9d4-4f3c-82ac-7e62ae8661b0.png)
