### ISSUE TITLE
500 Internal Error // Faraday::ConnectionFailed

### ISSUE THREAD

**Issue by GustavoPeredo** [html2rss/html2rss-web#608]
Hello, I recently cam across your project, while testing it out I'm having some issues. I created a folder with two files:

docker-compose.yml
```yaml
version: "3"
services:
  html2rss-web:
    image: gilcreator/html2rss-web
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./feeds.yml
        target: /app/config/feeds.yml
        read_only: true
    environment:
      - RACK_ENV=production
      - HEALTH_CHECK_USERNAME=health
      - HEALTH_CHECK_PASSWORD=please-set-YOUR-OWN-veeeeeery-l0ng-aNd-h4rd-to-gue55-Passw0rd!
     
```

and

feeds.yml
```yaml
stylesheets:
  - href: "/rss.xsl"
    media: "all"
    type: "text/xsl"
headers:
  "User-Agent": "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
feeds:
  # your custom feeds go here:
  example:
    channel:
      url: https://www.reuters.com/technology/
      language: en
      ttl: 360
      time_zone: UTC
    selectors:
      items:
        selector: '[class^="story-collection"] > li'
      title:
        selector: h3
      link:
        selector: a:first
        extractor: href
      description:
        selector: p

```

No matter which config example, it returns the same error (this is a screenshot when using 120 commits config):

![image](https://github.com/html2rss/html2rss-web/assets/30641461/38e9a649-c65c-424d-ae81-593a8eeb618e)

These are the logs:

```
[+] Building 0.0s (0/0)                                                                                                                                                                                              
[+] Running 1/0
 ✔ Container feeds-html2rss-web-1  Created                                                                                                                                                                      0.0s 
Attaching to feeds-html2rss-web-1
feeds-html2rss-web-1  | [1] Puma starting in cluster mode...
feeds-html2rss-web-1  | [1] * Puma version: 6.4.0 (ruby 3.2.2-p53) ("The Eagle of Durango")
feeds-html2rss-web-1  | [1] *  Min threads: 5
feeds-html2rss-web-1  | [1] *  Max threads: 5
feeds-html2rss-web-1  | [1] *  Environment: production
feeds-html2rss-web-1  | [1] *   Master PID: 1
feeds-html2rss-web-1  | [1] *      Workers: 2
feeds-html2rss-web-1  | [1] *     Restarts: (✔) hot (✖) phased
feeds-html2rss-web-1  | [1] * Preloading application
feeds-html2rss-web-1  | [1] * Listening on http://0.0.0.0:3000
feeds-html2rss-web-1  | [1] Use Ctrl-C to stop
feeds-html2rss-web-1  | [1] - Worker 0 (PID: 7) booted in 0.0s, phase: 0
feeds-html2rss-web-1  | [1] - Worker 1 (PID: 9) booted in 0.0s, phase: 0
feeds-html2rss-web-1  | source=rack-timeout id=80dcab76-8dda-4ea9-9e18-82e536d4da82 timeout=15000ms state=ready at=info
feeds-html2rss-web-1  | source=rack-timeout id=80dcab76-8dda-4ea9-9e18-82e536d4da82 timeout=15000ms service=5605ms state=completed at=info
```

What could be the issue?
