### ISSUE TITLE
feeds.yml not loaded using docker-compose.yml

### ISSUE THREAD

**Issue by haayman** [html2rss/html2rss-web#618]
I'm trying to run html2rss-web from docker using the docker-compose.yml provided, but when I open the web interface I just see the default example.rss, not mine.
![image](https://github.com/html2rss/html2rss-web/assets/683823/40a302de-a1c0-4734-90d6-b109a4db92dc)

There's not a lot of logging telling me what's going on, so this is also a feature request: display on startup the config that is loaded and how it is interpreted.

This is my feeds.yml, which is mounted to /app/config/feeds.yml. Could it be that this is not the correct location?

```
stylesheets:
  - href: "/rss.xsl"
    media: "all"
    type: "text/xsl"
headers:
  "User-Agent": "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
feeds:
  # your custom feeds go here:
  samengezondindeventer:
    channel:
      url: https://samengezondindeventer.nl/nieuws
      title: "Samen gezond in Deventer"
      ttl: 120
    selectors:
      items:
        selector: "article"
      title:
        selector: "h2 a"
      link:
        selector: "a"
        extractor: "href"
```
